### ISSUE TITLE
Date is cached in constructor

### ISSUE THREAD

**Issue by blacksonic** [emartech/escher-js#5]
If I instantiate the class, it stores the current Date. Problem comes when someone tries to sign a request after minutes of the instantiation, will get an expires message from the receiving part.

**Comment by boogie** [comment]
It is a known issue, all Escher implementations work like this. Pull requests are welcome, it would be great to see it fixed. :)

**Comment by ejstrobel** [comment]
I had the same problem in the java/scala lib. This was a huge pain to debug, since it works fine in tests and stops working after 15 minutes in production.

**Comment by boogie** [comment]
This commit fixes the issue: https://github.com/emartech/escher-js/commit/b844df6f028660acb645f06e9e05ac758c7a98ff

**Comment by szeist** [comment]
Fixed in release v1.0.0
